local   all     postgres                                 trust
host    all     postgres                  all            trust
host    all     db_migratior              all            password
host    all     db_rw                     all            password
host    all     db_ro                     all            password
host    all     db_rp                     all            password
host    all     db_np                     all            trust
host    all     db_ro_scram_sha256        all            scram-sha-256
hostssl all     db_ro_ssl                 all            password
